package com.insightself;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.DriverManager;
import java.util.Set;
import java.util.TreeSet;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayMigrationTest {
    private static final Set<String> REQUIRED_TABLES = Set.of(
            "users",
            "auth_sessions",
            "user_profiles",
            "bazi_results",
            "zodiac_results",
            "assessment_questions",
            "assessment_results",
            "ai_reports",
            "ai_chat_sessions",
            "ai_chat_messages",
            "flyway_schema_history"
    );

    @Test
    void h2MigrationCreatesCompleteTestSchema() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:flyway-contract-" + System.nanoTime() + ";DB_CLOSE_DELAY=-1";
        MigrateResult result = Flyway.configure()
                .dataSource(jdbcUrl, "sa", "")
                .locations("classpath:db/migration/h2")
                .load()
                .migrate();

        assertThat(result.migrationsExecuted).isEqualTo(1);
        try (var connection = DriverManager.getConnection(jdbcUrl, "sa", "");
             var statement = connection.createStatement();
             var rs = statement.executeQuery("""
                     SELECT LOWER(TABLE_NAME)
                     FROM INFORMATION_SCHEMA.TABLES
                     WHERE TABLE_SCHEMA = 'PUBLIC'
                     """)) {
            Set<String> tables = new TreeSet<>();
            while (rs.next()) {
                tables.add(rs.getString(1));
            }
            assertThat(tables).containsAll(REQUIRED_TABLES);
        }
    }

    @Test
    void sqliteMigrationCreatesCompleteDefaultRuntimeSchema() throws Exception {
        Path db = Files.createTempFile("insightself-flyway-", ".sqlite");
        Files.deleteIfExists(db);

        MigrateResult result = Flyway.configure()
                .dataSource("jdbc:sqlite:" + db.toAbsolutePath(), null, null)
                .locations("classpath:db/migration/sqlite")
                .load()
                .migrate();

        assertThat(result.migrationsExecuted).isEqualTo(1);
        try (var connection = DriverManager.getConnection("jdbc:sqlite:" + db.toAbsolutePath());
             var statement = connection.createStatement();
             var rs = statement.executeQuery("SELECT name FROM sqlite_master WHERE type = 'table'")) {
            Set<String> tables = new TreeSet<>();
            while (rs.next()) {
                tables.add(rs.getString(1));
            }
            assertThat(tables).containsAll(REQUIRED_TABLES);
        } finally {
            Files.deleteIfExists(db);
        }
    }

    @Test
    void mysqlMigrationScriptTargetsMysqlWithoutBecomingDefaultRuntimeSchema() throws Exception {
        String mysqlMigration = Files.readString(Path.of("src/main/resources/db/migration/mysql/V1__initial_schema.sql"));

        assertThat(mysqlMigration)
                .contains("ENGINE=InnoDB")
                .contains("DEFAULT CHARSET=utf8mb4")
                .contains("CREATE TABLE auth_sessions")
                .contains("CREATE TABLE ai_chat_messages")
                .doesNotContain("AUTOINCREMENT")
                .doesNotContain("GENERATED BY DEFAULT AS IDENTITY");
    }
}
