package com.example.insightself.ui.theme

import androidx.compose.ui.graphics.Color

val InsightPrimary = Color(0xFF5064F6)
val InsightPrimary2 = Color(0xFF22B8CF)
val InsightBackground = Color(0xFFF5F8FC)
val InsightBackground2 = Color(0xFFEFF8FF)
val InsightBackgroundGlow = Color(0xFFD8EEFF)
val InsightText = Color(0xFF111827)
val InsightMuted = Color(0xFF5F6675)
val InsightMutedLight = Color(0xFF969DAA)
val InsightStroke = Color(0x24111827)
val InsightCard = Color(0xF7FFFFFF)
val InsightCardStrong = Color(0xFFFFFFFF)
val InsightChip = Color(0x14FFFFFF)
val InsightChipSelected = Color(0x1F5B67FF)
val InsightTrack = Color(0xFFE8ECF1)
val InsightSuccess = Color(0xFF1FBF73)
val InsightSuccess2 = Color(0xFF59D98F)
val InsightWarning = Color(0xFFFFB020)
val InsightWarning2 = Color(0xFFFFCF6A)
val InsightDanger = Color(0xFFC03535)
val InsightMetal = Color(0xFF444A5C)
val InsightWater = Color(0xFF35B6FF)
val InsightLavender = Color(0xFFEEF0FF)
val InsightMint = Color(0xFFEAFBF2)
val InsightSky = Color(0xFFEAF8FF)
val InsightPeach = Color(0xFFFFF3E3)
