package com.insightself.dto;

import com.insightself.common.WellnessSafetyNotice;
import com.insightself.domain.AiReport;

import java.time.LocalDateTime;

public record AiReportResponse(
        Long id,
        Long userId,
        String reportText,
        String generatedBy,
        LocalDateTime createdAt,
        String sourceExplanation,
        String safetyNotice
) {
    public static AiReportResponse from(AiReport report) {
        return new AiReportResponse(
                report.getId(),
                report.getUserId(),
                report.getReportText(),
                report.getGeneratedBy(),
                report.getCreatedAt(),
                sourceExplanation(report.getGeneratedBy()),
                WellnessSafetyNotice.english()
        );
    }

    public static AiReportResponse from(AiReport report, String language) {
        return new AiReportResponse(
                report.getId(),
                report.getUserId(),
                report.getReportText(),
                report.getGeneratedBy(),
                report.getCreatedAt(),
                sourceExplanation(report.getGeneratedBy()),
                WellnessSafetyNotice.forLanguage(language)
        );
    }

    private static String sourceExplanation(String generatedBy) {
        if ("QWEN".equalsIgnoreCase(generatedBy)) {
            return "Generated by Qwen from compact structured InsightSelf context.";
        }
        if ("TEMPLATE".equalsIgnoreCase(generatedBy)) {
            return "Generated by the deterministic template fallback because the AI provider is not configured.";
        }
        return "Generated by the InsightSelf backend.";
    }
}
