CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
CREATE UNIQUE INDEX uk_users_username ON users (username);

CREATE TABLE auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_token_hash VARCHAR(64) NOT NULL,
    refresh_token_hash VARCHAR(64) NOT NULL,
    access_token_expires_at TIMESTAMP NOT NULL,
    refresh_token_expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP,
    revoked_at TIMESTAMP
);
CREATE UNIQUE INDEX idx_auth_sessions_access_token_hash ON auth_sessions (access_token_hash);
CREATE UNIQUE INDEX idx_auth_sessions_refresh_token_hash ON auth_sessions (refresh_token_hash);
CREATE INDEX idx_auth_sessions_user_id ON auth_sessions (user_id);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    gender VARCHAR(64),
    birth_date DATE NOT NULL,
    birth_time TIME,
    birth_place VARCHAR(128),
    birth_timezone VARCHAR(64),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    calendar_type VARCHAR(16) NOT NULL,
    preference VARCHAR(16) NOT NULL,
    ai_enabled BOOLEAN NOT NULL,
    language VARCHAR(8) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX uk_user_profiles_user_id ON user_profiles (user_id);

CREATE TABLE bazi_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    year_pillar VARCHAR(255),
    month_pillar VARCHAR(255),
    day_pillar VARCHAR(255),
    hour_pillar VARCHAR(255),
    wood_score INTEGER NOT NULL,
    fire_score INTEGER NOT NULL,
    earth_score INTEGER NOT NULL,
    metal_score INTEGER NOT NULL,
    water_score INTEGER NOT NULL,
    chart_json VARCHAR(16000),
    calculation_method VARCHAR(128),
    conclusion VARCHAR(1200),
    evidence VARCHAR(1200),
    suggestion VARCHAR(1200),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE zodiac_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    zodiac_sign VARCHAR(255) NOT NULL,
    insight_date DATE NOT NULL,
    emotion_score INTEGER NOT NULL,
    communication_score INTEGER NOT NULL,
    action_score INTEGER NOT NULL,
    chart_json VARCHAR(20000),
    calculation_method VARCHAR(128),
    suggestion VARCHAR(1200),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE assessment_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(32) NOT NULL,
    instrument_version VARCHAR(32) NOT NULL,
    item_key VARCHAR(64) NOT NULL,
    question_text VARCHAR(500) NOT NULL,
    question_text_zh VARCHAR(500),
    dimension VARCHAR(64) NOT NULL,
    reverse_score BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    source_note VARCHAR(256)
);

CREATE TABLE assessment_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    instrument_version VARCHAR(32) NOT NULL,
    result_label VARCHAR(64) NOT NULL,
    result_json VARCHAR(12000) NOT NULL,
    summary VARCHAR(1200),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ai_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    report_text VARCHAR(6000) NOT NULL,
    source_snapshot_json VARCHAR(30000) NOT NULL,
    generated_by VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ai_chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX uk_ai_chat_sessions_session_id ON ai_chat_sessions (session_id);

CREATE TABLE ai_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
